In [1]:
import numpy as np

In [2]:
class student:
    def __init__(self,name)->:
        self.name = name

SyntaxError: expected ':' (2343988391.py, line 2)

In [ ]:
lst=[1,2,3,4]
print(lst)
v = np.array([1,2,3,4])
print(v)
print("="*20)
m=np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
print(m.ndim)


[1, 2, 3, 4]
[1 2 3 4]
2


In [ ]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape(2,3)
print(vec)
print(mat)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
def array_reshape(arr, rows =- 1, cols =- 1):
    try:
        arr = np.array(arr)
        return arr.reshape(rows, cols)
    except (TypeError, ValueError) as e:
        raise ValueError(f"Invalid reshape operation: {e}")

array_reshape([1,2,3,4,5,6,7,8,9],3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
def convert_dtype(arr,dtype):
    
    if not isinstance(arr,np.ndarray):
        
    arr = np.array(arr)
    
    

In [ ]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.isclose(v1,v2,atol=3)

array([ True,  True,  True])

In [ ]:
lst=[1,2,3,4,5,6]
lst = np.array(lst)
print(lst)
zeros = np.zeros((2,3))
print(zeros)
ones = np.ones((2,3))
print(ones)

[1 2 3 4 5 6]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
range_array = np.arange(0,9)
print(range_array)
array_2= range_array.reshape(3,3)
print(array_2)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
range_array = np.arange(0,9,2)
print(range_array)

[0 2 4 6 8]


In [ ]:
line_space = np.linspace(0,10,5)
print(line_space)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
array_2 = np.random.randint(10,50,(3,2))
print(array_2)

[[24 27]
 [14 38]
 [41 43]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.dtype)

(2, 3)
int64


In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[-1])

1
6


In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr[0:2])
print(arr[-1:-5:-1])

[1 2]
[6 5 4 3]


In [ ]:
arr = np.array([[1,2,3],
               [4,5,6]])
print(arr[0,1])
print(arr[1,2])

2
6


In [ ]:
arr = np.array([[1,2,3],
               [4,5,6]])
print(arr[0:1,1:2])
print(arr[1:,2:])

[[2]]
[[6]]


In [4]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6])

In [ ]:
arr2 = np.fromiter((a for a in range(10)),int)

In [ ]:
np.empty([3,4],dtype= int)

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [ ]:
arr3=np.full([4,4],50)

In [ ]:
arr3.size

16

In [ ]:
len(arr3)

4

In [4]:
arr4 = np.array([[1,2,3],
                 [4,5,6]])

In [5]:
arr4 = arr4.astype('float')

In [6]:
arr4.size

6

In [7]:
len(arr4)

2

In [8]:
arr4.shape

(2, 3)

In [9]:
arr4.dtype

dtype('float64')

In [12]:
arr5 = arr4.tolist()

In [13]:
arr5

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [5]:
np.save("file",np.array([1,6,5,4,3,2]))

In [6]:
arr6 = np.load("file.npy")

In [9]:
arr6

array([1, 2, 3, 4, 5, 6])

In [8]:
arr6.sort()

In [23]:
arr7 = np.array([[1,2,3,4],
                [5,6,7,8]])

In [24]:
arr7

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# np.sort(arr7)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
arr = np.append(arr7,[9])

In [26]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr = np.arange(1,13).reshape(2,6)

In [28]:
arr


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [30]:
row = np.arange(13,19).reshape(1,6)

In [31]:
arr_row = np.append(arr,row,axis=0)

In [32]:
arr_row

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [33]:
column = np.arange(20,22).reshape(2,1)

In [34]:
arr_column = np.append(arr,column,axis = 1)

In [35]:
arr_column

array([[ 1,  2,  3,  4,  5,  6, 20],
       [ 7,  8,  9, 10, 11, 12, 21]])

In [ ]:
a = np.insert(arr,1,9)

In [37]:
a


array([ 1,  9,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
a = np.delete(arr,1)

In [40]:
a

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
arr3 = np.arange(0,9)

In [46]:
arr3.resize((3,4))

In [47]:
arr3

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 0, 0, 0]])

In [51]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
arr = np.array([list1,list2])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
gg = np.array([[1,2],
               [3,4],
               [5,6]])
print(gg)
print('*'*20)
print(gg.transpose(1,0))
print('*'*20)
print(gg.T)

[[1 2]
 [3 4]
 [5 6]]
********************
[[1 3 5]
 [2 4 6]]
********************
[[1 3 5]
 [2 4 6]]
